### ISSUE TITLE
TRYTOND_PASSWORD not working

### ISSUE THREAD

**Issue by ghost** [mbehrle/docker-tryton-server#1]
Hi,

I have been trying out your container, but the only way I have been able to set the db-admin password is via trytond.conf.

According to `trytond --help`
TRYTONPASSFILE (not TRYTOND_PASSFILE) specifies the file used to provide the admin password to use when initializing a database from the shell, I've not found any reference to specifying the  admin password in this way.

**Comment by mbehrle** [comment]
Thanks for the hint! Got this late because of weird github mail notfication....

Fixed in https://github.com/mbehrle/docker-tryton-server/commit/d60e63da3cf6f364c06c17a49a3836d62b0bfe91
